@Host = http://localhost:5207
@Base = {{Host}}/music/v2

@PlaylistFilename = save..m3u8
@Token = Br3eLY1DfgaQxZDeTIYZVA

###

GET {{Base}}/auth
Authorization: Bearer {{Token}}

###

GET {{Base}}/tracks
###
GET {{Base}}/tracks
Authorization: Bearer {{Token}}

###

GET {{Base}}/playlists
###
GET {{Base}}/playlists
Authorization: Bearer {{Token}}

###

GET {{Base}}/drafts
Authorization: Bearer {{Token}}
###
POST {{Base}}/draft
Authorization: Bearer {{Token}}
###
GET {{Base}}/draft/1/meta
Authorization: Bearer {{Token}}
###
PUT {{Base}}/draft/1/meta
Authorization: Bearer {{Token}}

{
    "title": "a",
    "artist": "b",
    "album": "c",
    "year": 2069,
    "trackNumber": 1,
    "trackCount": 1,
    "discNumber": 1,
    "discCount": 1,
    "links": [
        "https://soundcloud.com/furtrash/scene-kweenz",
        "https://youtu.be/aTmlhlXR-oE"
    ]
}
###
PUT {{Base}}/draft/1/art
Authorization: Bearer {{Token}}
Content-Type: image/jpeg

< D:/Downloads/a3621933057_0.jpg
###
PUT {{Base}}/draft/1/art
Authorization: Bearer {{Token}}
Content-Type: text/plain

https://f4.bcbits.com/img/a2999483571_0.png
###
GET {{Base}}/draft/1/files
Authorization: Bearer {{Token}}
###
POST {{Base}}/draft/1/file
Authorization: Bearer {{Token}}

https://soundcloud.com/furtrash/scene-kweenz
###
GET {{Base}}/draft/1/file/1
Authorization: Bearer {{Token}}
###
GET {{Base}}/draft/1/file/1/spectrogram
Authorization: Bearer {{Token}}
###
POST {{Base}}/draft/1/file
Authorization: Bearer {{Token}}

https://youtu.be/aTmlhlXR-oE
###
GET {{Base}}/draft/1/file/2
Authorization: Bearer {{Token}}
###
GET {{Base}}/draft/1/file/2/spectrogram
Authorization: Bearer {{Token}}
###
DELETE {{Base}}/draft/1/file/1
Authorization: Bearer {{Token}}
###
POST {{Base}}/draft/1/finalize/2
Authorization: Bearer {{Token}}
###
DELETE {{Base}}/draft/1
Authorization: Bearer {{Token}}

###

# TODO: caching
#DELETE {{Base}}/cache
#Authorization: Bearer {{Token}}

###
